
@echo off

REM !!! Generated by the fmp-cli 1.83.0.  DO NOT EDIT!

md PanoramicWander\Assets\3rd\fmp-xtc-panoramicwander

cd ..\vs2022
dotnet build -c Release

copy fmp-xtc-panoramicwander-lib-mvcs\bin\Release\netstandard2.1\*.dll ..\unity2021\PanoramicWander\Assets\3rd\fmp-xtc-panoramicwander\
